"""empty message

Revision ID: a5b0cf2f0f2e
Revises: f6e9f0391227
Create Date: 2020-11-18 12:57:50.572986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b0cf2f0f2e'
down_revision = 'f6e9f0391227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'get_push',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'get_push',
               existing_type=sa.String(length=1),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
